### ISSUE TITLE
[UI BUG] The edit function modal closes automatically when attempting to change the function.

### ISSUE THREAD

**Issue by rajat-durian** [checkmarble/marble#26] opened 2024-06-13 11:31 UTC
[marble_bug.webm](https://github.com/checkmarble/marble/assets/94341418/3311609f-7001-437f-9c01-6b823d754ff9)

Steps to reproduce - 

1. Add a function to a rule.
2. Save the rule
3. Click on edit function
4. Click on functions in the modal

**Comment by balzdur** [comment] 2024-07-22 08:38
Hi @rajat-durian, thank you for the detailed issue !

Sorry for the delay, the issue seems to be non reproductible on our side (probably addressed in our latest changes on the UI part). Can you confirm ?

**Comment by balzdur** [comment] 2024-11-05 10:51
I assume this is resolved. Fill free to ping me if it's not, and I'll reopen the issue

**Closed by balzdur** 2024-11-05 10:51 UTC
